// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AjusteJuego = { seccion: string, clave: string, 
/**
 * true/false, o un número (WindowMode: 0 pantalla completa, 1 ventana, 2 sin bordes; MinimapScale).
 */
valor: boolean | number, };
