// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fila de la tier list de aumentos de un campeón.
 */
export type AumentoFila = { id: number, nombre: string, icono: string, 
/**
 * "kSilver" | "kGold" | "kPrismatic"
 */
rareza: string, tier: number, perf: number, popular: number, };
