// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Icono } from "./Icono";
import type { Runas } from "./Runas";

/**
 * Build recomendada de un campeón en ARAM según OP.GG (la misma que usa OP.GG para ARAM: Caos).
 */
export type Build = { campeon: number, runas: Runas, hechizos: Array<Icono>, inicio: Array<Icono>, botas: Array<Icono>, nucleo: Array<Icono>, 
/**
 * Ítems que más se terminan comprando, fuera del núcleo y las botas.
 */
situacionales: Array<Icono>, 
/**
 * Orden de subida de habilidades, nivel por nivel ("Q", "W"...).
 */
habilidades: Array<string>, 
/**
 * Qué habilidad maximizar primero.
 */
prioridad: Array<string>, 
/**
 * Winrate del campeón y partidas analizadas.
 */
winrate: number, partidas: number, 
/**
 * Grieta: la posición de esta build y las posiciones en que se juega el campeón (la más jugada primero).
 */
posicion: string | null, posiciones: Array<string>, };
