// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CampeonInfo = { id: number, nombre: string, icono: string, 
/**
 * Tier en ARAM: Caos según OP.GG: 1 = mejor … 5.
 */
tier: number | null, puesto: number | null, };
