// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Carta = { id: number, nombre: string, icono: string, 
/**
 * 0 = S … 6 = F; None = OP.GG no tiene partidas de ese aumento con el campeón.
 */
tier: number | null, perf: number, 
/**
 * 1 = la mejor de las ofrecidas.
 */
puesto: number, mejor: boolean, 
/**
 * Mala o sin datos habiendo una buena en la mesa: conviene usar su botón de cambio.
 */
cambiar: boolean, x: number, y: number, };
