// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Config = { estilo: string, voz: boolean, arena: boolean, pausado: boolean, 
/**
 * "auto" (el del cliente del LoL), "es" o "en".
 */
idioma: string, 
/**
 * Calibración: desplazamiento vertical de las marcas, en píxeles a 1200 de alto.
 */
offset_y: number, 
/**
 * Calibración: tamaño de las marcas.
 */
escala: number, 
/**
 * Guarda una captura cada vez que detecta cartas (para reportar fallos o calibrar).
 */
grabar: boolean, autostart: boolean, 
/**
 * Deja el juego en "Sin bordes" solo (si alguien lo cambia, Xyra lo vuelve a poner con el juego cerrado).
 */
auto_bordes: boolean, 
/**
 * Importa las runas en cuanto te toca un campeón en la selección.
 */
auto_runas: boolean, 
/**
 * Cierra la ventana de Xyra al empezar la partida (queda en la bandeja, sin gastar memoria).
 */
cerrar_en_partida: boolean, };
