// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Carta } from "./Carta";
import type { Fase } from "./Fase";
import type { Seleccion } from "./Seleccion";

export type Estado = { fase: Fase, 
/**
 * Nombre del campeón en partida.
 */
campeon: string | null, 
/**
 * "KIWI" = ARAM: Caos, "CHERRY" = Arena.
 */
modo: string | null, cartas: Array<Carta>, seleccion: Seleccion | null, 
/**
 * None = no se pudo leer la configuración del juego.
 */
sin_bordes: boolean | null, idioma_cliente: string, ocr: string | null, version: string, };
