// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Fila = { id: number, nombre: string, icono: string, partidas: number, victorias: number, };
