// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Algo con nombre e ícono: un aumento, un ítem, una runa, un hechizo.
 */
export type Icono = { id: number, nombre: string, icono: string, };
