// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Maestria = { id: number, nombre: string, icono: string, nivel: number, puntos: number, };
