// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dónde se juega la build: ARAM (también la usa ARAM: Caos) o la Grieta del Invocador (normales y clasificatorias).
 */
export type ModoBuild = "aram" | "grieta";
