// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Maestria } from "./Maestria";
import type { Rango } from "./Rango";

export type Perfil = { nombre: string, tag: string, nivel: number, icono: string, 
/**
 * "LA1", "NA1"…
 */
region: string, 
/**
 * None si no tiene rango en Solo/Dúo.
 */
rango: Rango | null, 
/**
 * Los 5 campeones con más maestría.
 */
maestrias: Array<Maestria>, };
