// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rango de Solo/Dúo.
 */
export type Rango = { 
/**
 * "IRON" … "CHALLENGER" (la interfaz lo traduce y busca su emblema).
 */
liga: string, 
/**
 * "I" … "IV"; vacío en Maestro o más.
 */
division: string, lp: bigint, };
