// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fila } from "./Fila";
import type { Reciente } from "./Reciente";

export type Resumen = { partidas: number, victorias: number, campeones: Array<Fila>, aumentos: Array<Fila>, recientes: Array<Reciente>, };
