// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Icono } from "./Icono";

/**
 * Página de runas: árbol principal (4 runas, la primera es la clave), secundario (2) y fragmentos (3).
 */
export type Runas = { principal: Icono, secundaria: Icono, runas: Array<Icono>, secundarias: Array<Icono>, fragmentos: Array<Icono>, 
/**
 * % de victorias y de uso de esta página.
 */
winrate: number, uso: number, };
