// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CampeonInfo } from "./CampeonInfo";

/**
 * Selección de campeones: el tuyo y los de la banca (lo mismo que ves en el cliente).
 */
export type Seleccion = { campeon: CampeonInfo | null, banca: Array<CampeonInfo>, 
/**
 * Modo de la cola: "ARAM", "KIWI" (Caos), "CLASSIC" (Grieta), "CHERRY" (Arena)...
 */
modo: string, 
/**
 * Posición asignada en la Grieta ("top", "jungle", "mid", "adc", "support"); None en ARAM o elección a ciegas.
 */
posicion: string | null, };
